name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
      with:
          fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.16

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3.2.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
